### ISSUE TITLE
Is there any kind of "reset()" or "clear()" function ?

### ISSUE THREAD

**Issue by MarkusBordihn** [PencilCode/jquery-turtle#103]
For my use case I loading jquery and the jquery-turtle library one time and want to reused it for several movements.

$(q).home() works great to reset the position, but I don't found any function which remove the drafted lines / shapes or everything besides the turtle so that I could start with an clean screen without reloading the window or content.

**Comment by davidbau** [comment]
There is a cs() "clear screen" function.  Does it do what you want?

**Comment by MarkusBordihn** [comment]
Unfortunately its killing the turtle (custom image) as well.
Is there an easy way to regenerate the custom turtle image ?

Basically I need cs() with the option to keep the turtle (custom image).

**Comment by davidbau** [comment]
There is a cg() to just clear the "graphics" surface, which leaves text and
turtles alone.  Does that do the trick for you

**Comment by MarkusBordihn** [comment]
Does the trick. Thanks a lot. ;)
