### ISSUE TITLE
Piano bug(?)

### ISSUE THREAD

**Issue by 100benabbott** [PencilCode/jquery-turtle#90]
When transposing a song to Pencilcode, I may have stumbled across a bug/glitch.

In the last second of the song, [g,, ^a,, d, g,]/4 is played as [_g,, ^a,, d, _g,]/4

Is this something I am doing wrong or a bug? Note that I was able to fix this earlier in the song by switching some sharps and flats, but that doesn't work now.

http://benabbott.pencilcode.net/edit/Strength_of_a_Thousand_Men

**Comment by davidbau** [comment]
Accidentals apply to all notes of the same pitch until the end of the measure.  You can use "=" to make it natural again later.

Here is the part of the ABC standard that talks about it.
http://abcnotation.com/wiki/abc:standard:v2.1#accidental_directives

Pencil Code doesn't implement the whole standard, but it does follow this part.
